version: '3.3'

services:
   php:
     image: gliderlabs/registrator:latest
     command: "consul://consul:8500"
     depends_on:
       - consul
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock
   
   consul:
     image: consul:latest
     ports:
       - 40000:8500

